export const ARCADE_EVENTS = {
  GAME_START: 'GAME_START',
  GAME_OVER: 'GAME_OVER',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  
  // Round Progression
  ROUND_COMPLETE: 'ROUND_COMPLETE',
  MINIGAME_START: 'MINIGAME_START',
  
  // Encounters
  BOSS_ENCOUNTER: 'BOSS_ENCOUNTER',
  DEVIL_ENCOUNTER: 'DEVIL_ENCOUNTER',
  GOLDEN_DEVIL_ENCOUNTER: 'GOLDEN_DEVIL_ENCOUNTER',
  
  // RNG Events
  ANGEL_APPEAR: 'ANGEL_APPEAR',
  GOLDEN_ANGEL_START: 'GOLDEN_ANGEL_START',
  
  // Score Events
  MULTIPLIER_UP: 'MULTIPLIER_UP',
  THRESHOLD_REACHED: 'THRESHOLD_REACHED', // e.g. Hit 1M
  
  // Player Actions
  PLAYER_DAMAGE: 'PLAYER_DAMAGE',
  PLAYER_HEAL: 'PLAYER_HEAL',
  PLAYER_DEATH: 'PLAYER_DEATH'
};